[package]
name = "delatin-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"

[dev-dependencies]
bytemuck = "1"
image = "0.25"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
